# for local development
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'develop-stage'
    container_name: 'ppa-quasar'
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
    - '9000:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn && quasar dev"